urls.py
from __future__ import division
from __future__ import absolute_import

from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.simple import direct_to_template, redirect_to

from core.forms import EmailAuthenticationForm as AuthenticationForm
from registration.forms import SetPasswordForm

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
)

urlpatterns += patterns('',
    (r'^admin/django-ses/', include('django_ses.urls')),
)

if settings.USE_LANDING_PAGE:
    urlpatterns += patterns('',
        (r'^$', 'core.views.landing_page_wrapper', {'extra_context': {'login_form': AuthenticationForm}}),
    )
urlpatterns += patterns('',
    (r'^robots\.txt$', direct_to_template, {'template': 'robots.txt', 'mimetype': 'text/plain'}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^notifications/', include('notification.urls')),
    # Hardcoded urls to eventually get rid of
    (r'^sbc-bbq/$', redirect_to, {'url':'/events/6/'}),
    (r'^events/36/alrightt/$', redirect_to, {'url':'/techfair/'}),
    (r'^techfair/$', redirect_to, {'url': '/techfair/fair/'}),
    (r'^employer/signup/$', redirect_to, {'url':'/subscriptions/'}),
    (r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, {'set_password_form':SetPasswordForm, 'template_name' : 'password_reset_new.html', 'extra_context': {'login_form':AuthenticationForm}}, 'password_reset_confirm'),
    (r'^password/reset/complete/$', auth_views.password_reset_complete, {'template_name' : 'password_successfully_changed.html', 'extra_context': {'login_form':AuthenticationForm}}, 'password_reset_complete'),
    (r'^password/reset/done/$', auth_views.password_reset_done, {'template_name' : 'password_reset_done.html', 'extra_context': {'login_form':AuthenticationForm}}, 'password_reset_done'),
    (r'^ckeditor/', include('ckeditor.urls')),
    (r'^sentry/', include('sentry.web.urls')),
     url(r'zebra/',   include('zebra.urls',  namespace="zebra",  app_name='zebra') )
)
urlpatterns += patterns('newsletter.views',
    (r'^newsletter/(?P<year>\d+)/(?P<month>\w+)/$', 'newsletter', {}, 'newsletter'),
)
urlpatterns += patterns('core.views',
    (r'^$', 'home', {}, 'home'),
    (r'^favicon\.ico/$', redirect_to, {'url':'%simages/favicon.ico' % settings.STATIC_URL}),
    (r'^contact-us/$', 'contact_us', {}, 'contact_us'),
    (r'^terms/$', direct_to_template, {'template':'terms.html'}, 'terms'),
    (r'^terms/agree/$', 'terms_agree', {}, 'terms_agree'),
    (r'^help/$', 'help_center', {'extra_context': {'login_form': AuthenticationForm}}, 'help_center'),
    # Tutorials links to help center because I just put them there for now
    #(r'^help/tutorials/$', 'help_center', {'extra_context': {'login_form': AuthenticationForm}}, 'tutorials'),
    (r'^help/faq/$', 'faq', {'extra_context': {'login_form': AuthenticationForm}}, 'faq'),
    (r'^help/tutorials/(?P<slug>[0-9a-zA-Z-]+)/$', 'tutorial', {'extra_context': {'login_form': AuthenticationForm}}, 'tutorial'),
    (r'^about/$', 'about', {'extra_context': {'login_form': AuthenticationForm}}, 'about'),
    (r'^unsupported-browser/$', direct_to_template, { 'template' : 'browser_not_supported.html' }, 'unsupported_browser'),
    (r'^check-email-availability/$', 'check_email_availability', {}, 'check_email_availability'),
    (r'^check-employer-uniqueness/$', 'check_employer_uniqueness', {}, 'check_employer_uniqueness'),
    (r'^check-employer-campus-org-check-slug-uniqueness/$', 'check_employer_campus_org_slug_uniqueness', {}, 'check_employer_campus_org_slug_uniqueness'),    
    (r'^check-language-uniqueness/$', 'check_language_uniqueness', {}, 'check_language_uniqueness'),
    (r'^check-event-name-uniqueness/$', 'check_event_name_uniqueness', {}, 'check_event_name_uniqueness'),
    (r'^check-website/$', 'check_website', {}, 'check_website'),
    (r'^get-location-guess/$', 'get_location_guess', {}, 'get_location_guess'),
    (r'^get-location-suggestions/$', 'get_location_suggestions', {}, 'get_location_suggestions'),
    (r'^notification/count$', 'get_notice_unseen_count', {}, 'get_notice_unseen_count'),
    (r'^cache-status/$', 'cache_status', {}, 'cache_status'),
)
urlpatterns += patterns('campus_org.views',
    (r'^campus-org/registration/$', 'campus_org_registration', {'extra_context': {'password_min_length': settings.PASSWORD_MIN_LENGTH}}, "campus_org_registration"),
    (r'^campus-org/info/$', 'campus_org_info_dialog', {}, 'campus_org_info_dialog'),
    (r'^campus-org/check-uniqueness/$', 'check_campus_org_uniqueness', {}, 'check_campus_org_uniqueness'),
    (r'^campus-org/profile/$', 'campus_org_profile', {}, "campus_org_profile"),
    (r'^campus-org/account/$', 'campus_org_account', {'extra_context':{'password_min_length': settings.PASSWORD_MIN_LENGTH}}, 'campus_org_account'),
    (r'^campus-org/account/preferences/$', 'campus_org_account_preferences', {}, 'campus_org_account_preferences'),
    (r'^campus-org/registration/complete/$', 'campus_org_registration_complete', {}, 'campus_org_registration_complete'),
)
urlpatterns += patterns('registration.views',
    (r'^login/$', 'login', {'extra_context': {'authentication_form': AuthenticationForm}}, 'login'),
    (r'^super-login/$', 'super_login', {}, 'super_login'),
    (r'^logout/$', 'logout', {'login_url':'/?action=logged-out'}, 'logout'),
    (r'^password/change/$','password_change', {}, 'password_change'),
    (r'^resend_activation_email/$','resend_activation_email', {}, 'resend_activation_email'),
    (r'^password/reset/$', 'password_reset', {'extra_context': {'password_min_length': settings.PASSWORD_MIN_LENGTH, 'login_form':AuthenticationForm}}, 'password_reset'),
    (r'^activation/complete/$', direct_to_template, { 'extra_context': {'login_form':AuthenticationForm}, 'template': 'activation_complete.html' }, 'activation_complete'),
    (r'^activation/(?P<activation_key>\w+)/$', 'activate_user', {'extra_context': {'login_form': AuthenticationForm}}, 'student_activation'),

    )
urlpatterns += patterns('subscription.views',
    (r'^subscription/checkout/(?P<plan>\w+)/$', 'checkout', {}, 'checkout'),
    (r'^subscription/change/$', 'subscription_change', {}, 'subscription_change'),
    (r'^subscription/upgrade/(?P<subscription_type>\w+)/$', 'subscription_upgrade', {}, 'subscription_upgrade'),
    (r'^subscription/cancel/$', 'subscription_cancel', {}, 'subscription_cancel'),
    (r'^subscription/billing-cycle/change/$', 'subscription_billing_cycle_change', {}, 'subscription_billing_cycle_change'),
    (r'^account/request/$', 'account_request', {}, 'account_request'),
    (r'^payment/change/$', 'payment_change', {}, 'payment_change'),
    (r'^payment/cvc/help/$', direct_to_template, { 'template': 'payment_cvc_help_dialog.html' }, 'payment_cvc_help'),
    (r'^payment/forget/$', 'payment_forget', {}, 'payment_forget'),
    (r'^receipt/view/(?P<charge_id>\w+)/$', 'receipt_view', {}, 'receipt_view'),
    (r'^receipts/view/$', 'receipts_view', {}, 'receipts_view'),
    (r'^subscriptions/$', 'subscriptions', {'extra_context': {'login_form':AuthenticationForm}}, 'subscriptions'),
    (r'^webhooks/$', 'webhooks', {}, 'webhooks'),
    (r'^webhooks/v2/$', 'webhooks_v2', {}, 'webhooks_v2'),
)
urlpatterns += patterns('events.views',
    (r'^events/short-slug-uniqueness/$', 'events_check_short_slug_uniqueness', {}, 'events_check_short_slug_uniqueness'),
    (r'^events/(?P<id>\d+)/(?P<slug>[0-9a-zA-Z-]+)/$', 'event_page', {'extra_context': {'login_form':AuthenticationForm}}, 'event_page'),
    (r'^events/(?P<id>\d+)/$', 'event_page_redirect', {}, 'event_page_redirect'),
    (r'^events/export/$', 'event_list_export', {}, 'event_list_export'),
    (r'^events/admin/campusorg/upload-recruiter-list/$', 'event_upload_recruiters_list', {}, 'event_upload_recruiters_list'),
    (r'^events/export/download/$', 'event_list_download', {}, 'event_list_download'),
    (r'^events/export/completed/$', 'event_list_export_completed', {}, 'event_list_export_completed'),
    (r'^events/checkin/(?P<event_id>\d+)$', 'event_checkin', {}, 'event_checkin'),
    (r'^events/checkin/count/$', 'event_checkin_count', {}, 'event_checkin_count'),
    (r'^events/raffle-winner/$', 'event_raffle_winner', {}, 'event_raffle_winner'),
    (r'^events/rsvp/(?P<event_id>\d+)$', 'event_rsvp', {}, 'event_rsvp'),
    (r'^events/rsvp/message/$', 'event_rsvp_message', {}, 'event_rsvp_message'),
    (r'^events/drop/(?P<event_id>\d+)$', 'event_drop', {}, 'event_drop'),
    (r'^events/e/$', 'events_by_employer', {}, 'events_by_employer'),
    (r'^events/i/$', 'event_invite', {}, 'event_invite'),
    (r'^events/archive/(?P<id>\d+)$', 'event_archive', {}, 'event_archive'),
    (r'^events/new/$', 'event_new', {}, 'event_new'),
    (r'^events/cancel/(?P<id>\d+)$', 'event_cancel', {}, 'event_cancel'),
    (r'^events/edit/(?P<id>\d+)$', 'event_edit', {}, 'event_edit'),
    (r'^events/schedule/$', 'event_schedule', {}, 'event_schedule'),
    (r'^rolling-deadline/end/(?P<id>\d+)$', 'rolling_deadline_end', {}, 'rolling_deadline_end'),
    (r'^events/$', redirect_to, {'url':'/events/upcoming/'}, 'upcoming_events'),
    (r'^events/(?P<category>\w+)/$', 'events', {}, 'events'),
    (r'^event/(?P<event_id>\d+)/download-participant-resumes/$', 'download_event_participant_resumes', {}, 'download_event_participant_resumes')
)
urlpatterns += patterns('student.views',
    (r'^signup/$', 'student_registration', {'extra_context': {'password_min_length': settings.PASSWORD_MIN_LENGTH, 'login_form':AuthenticationForm}}, "student_registration"),
    (r'^signup/quick/$', 'student_quick_registration', {}, 'student_quick_registration'),

employer/forms.py
from __future__ import division
from __future__ import absolute_import

from django import forms
from django.conf import settings as s
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

from ckeditor.widgets import CKEditorWidget

from core import messages as m
from core.choices import NO_YES_CHOICES
from core.form_helpers import decorate_bound_field
from core.models import Industry, EmploymentType
from core.view_helpers import employer_campus_org_slug_exists
from core.widgets import UmSelectWidget
from employer.models import RecruiterPreferences, StudentFilteringParameters, Employer
from employer import enums as employer_enums
from student.form_helpers import student_lists_as_choices
from student.forms import StudentBaseAttributeForm

decorate_bound_field()

class CreateEmployerForm(forms.ModelForm):
    name = forms.CharField(label="Name:", max_length=42)
    industries = forms.ModelMultipleChoiceField(label="Industries:", queryset = Industry.objects.all())
    
    class Meta:
        fields = ('name',
                  'industries')
        model = Employer
    
    def clean_name(self):
        name = self.cleaned_data['name']
        try:
            Employer.objects.get(name=name)
            raise forms.ValidationError("This employer already exists.")
        except Employer.DoesNotExist:
            pass
        return self.cleaned_data['name']

    def clean_industries(self):
        industries = self.cleaned_data['industries']
        if len(industries) > s.EP_MAX_INDUSTRIES:
            raise forms.ValidationError("An employer cannot be in more than 5 industries.")
        return self.cleaned_data['industries']
            
class RecruiterForm(forms.ModelForm):
    email = forms.EmailField(label="Email:", max_length = 75)
    first_name = forms.CharField(label="First Name:", max_length=42, required=True)
    last_name = forms.CharField(label="Last Name:", max_length=42, required=True)
    password1 = forms.CharField(label="Choose Password:", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password:", widget=forms.PasswordInput)
    
    class Meta:
        fields = ('email',
                  'first_name',
                  'last_name')
        model = User

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            raise forms.ValidationError(_("The two passwords don't match."))
        return password2

    def save(self, commit=True):
        user = super(RecruiterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
                
class EmployerProfileForm(forms.ModelForm):
    name = forms.CharField(label="Company Name:", max_length=42)
    slug = forms.SlugField(label="Short URL:", max_length=42)
    industries = forms.ModelMultipleChoiceField(label="Relevant Industries:", queryset=Industry.objects.all())
    description = forms.CharField(widget=CKEditorWidget(attrs={'tabindex':5}))
    offered_job_types = forms.ModelMultipleChoiceField(label="Offered Job Types:", queryset=EmploymentType.objects.all(), required=False)
    careers_website = forms.URLField(label="Careers Website:", required=False)
    visible = forms.BooleanField(widget = forms.Select(choices=((True, 'Yes'), (False, 'No'))), required=False)
    class Meta:
        fields = ('name',
                  'slug', 
                  'industries',
                   'description',
                   'offered_job_types',
                   'careers_website',
                   'visible')
        model = Employer
    
    def clean_industries(self):
        if len(self.cleaned_data.get("industries")) > s.EP_MAX_INDUSTRIES:
            raise forms.ValidationError(_(m.max_industries_exceeded))
        return self.cleaned_data['industries']
    
    def clean_slug(self):
        if self.cleaned_data['slug']:
            if employer_campus_org_slug_exists(self.cleaned_data['slug'], employer=self.instance):
                raise forms.ValidationError(m.slug_already_taken)
        return self.cleaned_data['slug']

class DeliverResumeBookForm(forms.Form):
    name = forms.CharField(label="Resume Book Name:", max_length=42, required=False)
    emails = forms.CharField(label="Recipient Emails:", max_length=2000, widget=forms.Textarea(), required=False)
        
class StudentSearchForm(forms.Form):
    query = forms.CharField(max_length = 50, widget=forms.TextInput(attrs={'id':'query_field', 'placeholder':'Search by name, keyword, skill, etc..'}))
    
class StudentDefaultFilteringParametersForm(StudentBaseAttributeForm):
    older_than_21 = forms.ChoiceField(label="Must be older than 21:", choices = NO_YES_CHOICES, required = False)
    gpa = forms.DecimalField(label="Minimum GPA:", min_value = 0, max_value = 5, max_digits=5, widget=forms.TextInput(attrs={'class':'readonly'}), required = False)
    act = forms.IntegerField(label="Minimum ACT:", max_value = 36, widget=forms.TextInput(attrs={'class':'readonly'}), required = False)
    sat_t = forms.IntegerField(label="Minimum SAT:", max_value = 2400, min_value = 600, widget=forms.TextInput(attrs={'class':'readonly'}), required = False)
    sat_m = forms.IntegerField(label="Minimum SAT Math:", max_value = 800, min_value = 200, widget=forms.TextInput(attrs={'class':'readonly'}), required = False)
    sat_v = forms.IntegerField(label="Minimum SAT Verbal:", max_value = 800, min_value = 200, widget=forms.TextInput(attrs={'class':'readonly'}), required = False)
    sat_w = forms.IntegerField(label="Minimum SAT Writing:", max_value = 800, min_value = 200, widget=forms.TextInput(attrs={'class':'readonly'}), required = False)

    class Meta:
        fields = ( 'schools',
                   'majors',
                   'degree_programs',
                   'graduation_years',
                   'gpa',
                   'act',
                   'sat_t',
                   'sat_m',
                   'sat_v',
                   'sat_w',
                   'employment_types',
                   'previous_employers',
                   'industries_of_interest',
                   'campus_involvement',
                   'languages',
                   'countries_of_citizenship',
                   'older_than_21')
        model = StudentFilteringParameters

class StudentFilteringForm(StudentDefaultFilteringParametersForm):
    ordering = forms.ChoiceField(label="Order Results By:", choices = employer_enums.ORDERING_CHOICES, required = False)
    results_per_page = forms.ChoiceField(label="Results Per Page:", choices = employer_enums.RESULTS_PER_PAGE_CHOICES, required = False)

    def __init__(self, *args, **kwargs):
        super(StudentFilteringForm, self).__init__(*args, **kwargs)
        self.fields['student_list'] = forms.ChoiceField(widget = UmSelectWidget, choices = student_lists_as_choices(kwargs.get('initial').get('has_at_least_premium', ''), kwargs.get('initial').get('recruiter_id', '')))

class RecruiterPreferencesForm(forms.ModelForm):
    default_student_result_ordering = forms.ChoiceField(label="Default Student Result Ordering:", choices = employer_enums.ORDERING_CHOICES, required = False)
    default_student_results_per_page = forms.ChoiceField(label="Default Results Per Page:", choices = employer_enums.RESULTS_PER_PAGE_CHOICES, required = False)
    
    class Meta:
        fields = ("email_on_rsvp_to_public_event",
                  "email_on_rsvp_to_private_event",
                  "default_student_results_per_page",
                  "default_student_result_ordering" )
        model = RecruiterPreferences

employer/templates/employer_account_delete.html
<div class="dialog_content_wrapper">
    <h3>Are you sure you want to delete your account?</h3>
    <p>
        Your credentials can always be re-created by another recruiter.
    </p>
    <p>
        <strong>However</strong>, your resume book history will be forever lost.
    </p>
    <div class="button_wrapper_with_margins">
        <a class="button close_dialog_link">Cancel</a>
        <a class="button" id="delete_account_confirmation_link">Yes, I'm sure</a>
    </div>
</div>

employer/templates/employer_event_snippet.html
<div class="name">
    <span class="type">{{event.type}}</span> {{event.name}}
    <div class="datetime">
        {% if event.start_datetime %}
        <span class="start">{{event.start_datetime|date:"D n/j/y P"}}</span> - 
        {% endif %}
        <span class="end">
            {% ifequal event.start_datetime.day event.end_datetime.day %}
            {% ifequal event.start_datetime.month event.end_datetime.month %}
            {% ifequal event.start_datetime.year event.end_datetime.year %}
                {{event.end_datetime|date:"P"}}
            {% endifequal %}{% endifequal %}
            {% else %}
                {{event.end_datetime|date:"D n/j/y P"}}
            {% endifequal %}
        </span>
    </div>
</div>
{% if edit %}
<div class="edit">
<p><a href="{% url event_page id=event.id,slug=event.slug %}">View Description</a></p>
<p>
    <a href="{% url employer_edit_event id=event.id %}">Edit</a>
    <a href="{% url employer_delete_event id=event.id %}" class="delete-event-link">Delete</a>
</p>
</div>
{% endif %}
<div class="details">
    {% if event.location %}
    <div>
        <strong>Location:</strong>
        <span class="location">{{event.location}}</span>
    </div>
    {% endif %}
    {% if event.description %}
    <div>{{event.description}}</div>
    {% endif %}
</div>

employer/templates/employer_logo.html
{% if employer.logo %}
    <div data-employer-name="{{employer}}" class="attending_employer">
        {% if user.is_anonymous or user.student %}
            {% if employer.visible %}
                <a href="{{employer.get_absolute_url}}">
            {% endif %}
        {% endif %}
        <img title="{{employer}}" alt="{{employer}}" src=
        {% if employer_logo %}
            "{{employer_logo}}"
        {% else %}
            "{{MEDIA_URL}}{{employer.logo}}"
        {% endif %}
        >
        {% if user.is_anonymous or user.student %}
            {% if employer.visible %}
                </a>
            {% endif %}
        {% endif %}
    </div>
{% else %}
    <div data-employer-name="{{employer}}" class="no_logo attending_employer">
        <span>{{employer}}</span>
    </div>
{% endif %}

employer/templates/employer_profile_preview.html
{% extends "base.html" %}

{% block title %}
{{employer}} |
{% endblock %}

{% block metadata %}
{{block.super}}
{% load compress %}
{% load text_snippet %}
{% compress css %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/employer/employer_industries.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}css/employer/employer_profile_preview.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}css/events/event_snippet.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}css/events/rolling_deadline_end_dialog.css" />
{% endcompress %}
<script>
    var SUBSCRIBE_TOOLTIP = "{% text_snippet 'subscribe_tooltip' %}";
    var EVENT_ARCHIVED = "{% text_snippet 'event_archived' %}";
    var DEADLINE_ARCHIVED = "{% text_snippet 'deadline_archived' %}";
    var EVENT_CANCELLED = "{% text_snippet 'event_cancelled' %}";
    var DEADLINE_CANCELLED = "{% text_snippet 'deadline_cancelled' %}";
    var ROLLING_DEADLINE_ENDED = "{% text_snippet 'rolling_deadline_ended' %}";
</script>
{% compress js %}
<script type="text/javascript" src="{{ STATIC_URL }}js/employer/employer_profile_preview.js"></script>
<script src="{{ STATIC_URL }}js/events/event_archive.js"></script>
<script src="{{ STATIC_URL }}js/events/event_cancel_dialog.js"></script>
<script src="{{ STATIC_URL }}js/events/rolling_deadline_end_dialog.js"></script>
{% endcompress %}
{% endblock %}

{% block content_area %}
<div class="left_side_container">
    {% include "employer_side_nav.html" %}
</div>
<div class="with_side_nav no_top_margin">
    {% include "employer_details.html" with isnotajax="True" preview="True" %}</p>
</div>
{% endblock %}

employer/templates/employer_recruiter_new.html
<div class="dialog_content_wrapper">
    <h3>Create new recruiter credentials by filling out the fields below.</h3>
    <p class="centered">The credentials will be immediately ready for login.</p>
    <form id="create_recruiter_form" method='POST' action="{% url employer_recruiter_new %}">
        {% csrf_token %}
        <table class="form_table">
            {% for field in form %}
                <tr>
                    <th>{{ field.label_tag }}</th>
                    <td>
                        <div class="errorspace">{{ field.errors }}</div>
                        {{ field }}
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="2" class="error_section centered error">
                    {{form.non_field_errors}}
                </td>
            </tr>
            <tr>
                <td class="centered button_cell" colspan="2">
                    <a class="button close_dialog_link">Cancel</a>
                    <input class="button" type='submit' value='Create Credentials'>
                    <img class='ajax_form_submit_loader' src='{{ STATIC_URL }}images/loaders/s_ajax.gif'>
                </td>
            </tr>
        </table>
    </form>
</div>

employer/templates/employer_setup_default_filtering.html
{% extends "base.html" %}

{% block title %}
Setup Automatic Filtering |
{% endblock %}

{% block metadata %}
<!-- JQuery MultiSelect Widget -->
<script type="text/javascript" src="{{ STATIC_URL }}lib/jquery_multiselect/jquery_multiselect_min.js"></script>
<link rel="stylesheet" href="{{ STATIC_URL }}lib/jquery_multiselect/jquery_multiselect.css" />

<!-- JQuery MultiSelect Widget Filtering Plugin -->
<script type="text/javascript" src="{{ STATIC_URL }}lib/jquery_multiselect/jquery_multiselect_filter_min.js"></script>
<link rel="stylesheet" href="{{ STATIC_URL }}lib/jquery_multiselect/jquery_multiselect_filter.css" />

<!-- Custom -->
<link rel="stylesheet" href="{{ STATIC_URL }}css/employer/employer_students_default_filtering.css" />
<script type="text/javascript" src="{{ STATIC_URL }}javascript/employer/employer_students_default_filtering.js">
</script>

<!--datetime_field media-->
{{form.media}}
{% endblock %}

{% block content_area %}
<div id="new_event_form_block" class="main_block no_top_margin">
    <div class="main_block_header">
        <img class="main_block_header_icon" src="{{ STATIC_URL }}images/icons/magnifier.png"/>
        <span class="main_block_header_title">Set Up Default Filtering</span>
    </div>
    <div class="main_block_content">
        <div class="section content">
            <h3>How It Works</h3>
            <p>Here, you'll be able to set default parameters for <a href="{% url employer_students %}">student filtering</a>. Instead of starting filtering from scratch each time, set those parameters here, and they will be pre-set for you. For example, use these settings if you are only interested in students who are juniors and seniors with a GPA over 4.2.</p>
            <p>Additionally, you will get notified each time new students match your default filtering parameters. </p>
            <p>
                To customize how you will be notified,
                <a href="javascript:void(0)">change your preferences</a>.
            </p>
        </div>
        <form id="default_filtering_parameters_form" method="POST" action="">
            {% csrf_token %}
            <div class="section">
                <h3>I'm looking for students who...</h3>
                <table class="form_table">
                    <tr>
                        <th><label for="id_majors">are majoring in:</label></th>
                        <td>{{form.majors}}</td>
                    </tr>
                    <tr>
                        <th><label for="id_industries_of_interest">are interested in:</label></th>
                        <td>{{form.industries_of_interest}}</td>
                    </tr>
                    <tr>
                        <th><label for="id_previous_employers">have worked for:</label></th>
                        <td>{{form.previous_employers}}</td>
                    </tr>
                    <tr>
                        <th><label for="id_languages">know the languages:</label></th>
                        <td>{{form.languages}}</td>
                    </tr>
                    <tr>
                        <th><label for="id_campus_orgs">are involved in:</label></th>
                        <td>{{form.campus_orgs}}</td>
                    </tr>
                    <tr>
                        <th><label for="id_graduation_years">are graduating in:</label></th>
                        <td>{{form.graduation_years}}</td>
                    </tr>
                    <tr>
                        <th><label for="id_school_years">are in the year:</label></th>
                        <td>{{form.school_years}}</td>
                    </tr>
                    <tr>
                        <th><label for="id_looking_for_internship">are looking for an internship:</label></th>
                        <td>{{form.looking_for_internship}}</td>
                    </tr>
                    <tr>
                        <th><label for="id_looking_for_fulltime">are looking for fulltime:</label></th>
                        <td>{{form.looking_for_fulltime}}</td>
                    </tr>
                    <tr>
                        <th><label for="id_older_than_18">are older than 18:</label></th>
                        <td>{{form.older_than_18}}</td>
                    </tr>
                    <tr>
                        <th><label for="id_citizen">are citizens:</label></th>
                        <td>{{form.citizen}}</td>
                    </tr>
                </table>
            </div>
            <div class="section">
                <h3>..and have the following minimums.</h3>
                <div class="errorspace"></div>
                <div>
                    <label for="id_gpa">GPA:</label>
                    {{form.gpa}}
                </div>
                <div class="errorspace"></div>
                <div>
                    <label for="id_sat">SAT:</label>
                    {{form.sat}}
                </div>
                <div class="errorspace"></div>
                <div>
                    <label for="id_act">ACT:</label>
                    {{form.act}}
                </div>
            </div>
            <div class="button_wrapper_no_margins">
                <input id="default_filtering_parameters_form_submit_button" class="button" type='submit' value='Save'>
            </div>
        </form>
    </div>
</div>
{% endblock %}